export const events = [
  {
    name: "City Marathon",
    date: "2024-01-12",
    type: "other",
    otherType: "marathon",
    mode: "offline",
    result: "participated",
    venue: "New York",
    proof: "https://example.com/images/marathon.jpg",
    isVerified: null,
  },
  {
    name: "Hackathon 2024",
    date: "2024-02-18",
    type: "hackathon",
    otherType: "",
    mode: "offline",
    result: "won",
    venue: "San Francisco",
    proof: "https://example.com/images/hackathon.jpg",
    isVerified: null,
  },
  {
    name: "Art Exhibition",
    date: "2024-03-22",
    type: "other",
    otherType: "exhibition",
    mode: "offline",
    result: "participated",
    venue: "Paris",
    proof: "https://example.com/images/art_exhibition.jpg",
    isVerified: null,
  },
  {
    name: "Science Fair",
    date: "2024-04-10",
    type: "other",
    otherType: "fair",
    mode: "offline",
    result: "won",
    venue: "Tokyo",
    proof: "https://example.com/images/science_fair.jpg",
    isVerified: null,
  },
  {
    name: "Music Festival",
    date: "2024-05-05",
    type: "other",
    otherType: "festival",
    mode: "offline",
    result: "participated",
    venue: "London",
    proof: "https://example.com/images/music_festival.jpg",
    isVerified: null,
  },
  {
    name: "Food Festival",
    date: "2024-06-14",
    type: "other",
    otherType: "festival",
    mode: "offline",
    result: "participated",
    venue: "Rome",
    proof: "https://example.com/images/food_festival.jpg",
    isVerified: null,
  },
  {
    name: "Tech Conference",
    date: "2024-07-19",
    type: "other",
    otherType: "conference",
    mode: "offline",
    result: "won",
    venue: "Berlin",
    proof: "https://example.com/images/tech_conference.jpg",
    isVerified: null,
  },
  {
    name: "Film Festival",
    date: "2024-07-25",
    type: "other",
    otherType: "festival",
    mode: "offline",
    result: "participated",
    venue: "Cannes",
    proof: "https://example.com/images/film_festival.jpg",
    isVerified: null,
  }
  ];


export const requests = [
  {
    studentName: "Nikhil Kumar",
    class: "CSE A",
    name: "City Marathon",
    date: "2024-01-12",
    type: "other",
    otherType: "marathon",
    mode: "offline",
    result: "participated",
    venue: "New York",
    proof: "https://example.com/images/marathon.jpg",
    isVerified: null,
  },
  {
    studentName: "Nikhil Kumar",
    class: "CSE A",
    name: "Hackathon 2024",
    date: "2024-02-18",
    type: "hackathon",
    otherType: "",
    mode: "offline",
    result: "won",
    venue: "San Francisco",
    proof: "https://example.com/images/hackathon.jpg",
    isVerified: null,
  },
  {
    studentName: "Nikhil Kumar",
    class: "CSE A",
    name: "Art Exhibition",
    date: "2024-03-22",
    type: "other",
    otherType: "exhibition",
    mode: "offline",
    result: "participated",
    venue: "Paris",
    proof: "https://example.com/images/art_exhibition.jpg",
    isVerified: null,
  },
  {
    studentName: "Nikhil Kumar",
    class: "CSE A",
    name: "Film Festival",
    date: "2024-07-25",
    type: "other",
    otherType: "festival",
    mode: "offline",
    result: "participated",
    venue: "Cannes",
    proof: "https://example.com/images/film_festival.jpg",
    isVerified: null,
  }
]